@ECHO OFF
SET WEB_PORT=5173
SET SERVER_PORT=5174
SET INPUT=%~n1
IF /I '%INPUT%'=='devbox' (
ECHO "%WEB_PORT% => %SERVER_PORT%"
) ELSE (
SET EXTRA_DOCKER_COMMANDS=%EXTRA_DOCKER_COMMANDS% --publish %WEB_PORT%:%SERVER_PORT%
)
