//
// This file is generated. Do not edit manually.
//
// @applicationName: GreenOnion.API
// @applicationDescription: GreenOnion.API - 1.0.0.0
// @applicationVersion: 1.0.0.0
// @generatedDate: 2025/07/26
//


// Models
export { ContentReference } from "./ContentReference";
export type { IContentReference } from "./IContentReference";
export { FilterParameter } from "./FilterParameter";
export type { IFilterParameter } from "./IFilterParameter";
export { OrderDirections } from "./OrderDirections";
export type { IOrderDirections } from "./IOrderDirections";
export { MessageLevels } from "./MessageLevels";
export type { IMessageLevels } from "./IMessageLevels";
export { ResultMessage } from "./ResultMessage";
export type { IResultMessage } from "./IResultMessage";
export { FileHeader } from "./FileHeader";
export type { IFileHeader } from "./IFileHeader";
export { FileHeaderData } from "./FileHeaderData";
export type { IFileHeaderData } from "./IFileHeaderData";
export { FileStatus } from "./FileStatus";
export type { IFileStatus } from "./IFileStatus";
export { MappingFieldData } from "./MappingFieldData";
export type { IMappingFieldData } from "./IMappingFieldData";
export { ProductCheck } from "./ProductCheck";
export type { IProductCheck } from "./IProductCheck";
export { ProductGtinAllocationModel } from "./ProductGtinAllocationModel";
export type { IProductGtinAllocationModel } from "./IProductGtinAllocationModel";
export { ProductTableField } from "./ProductTableField";
export type { IProductTableField } from "./IProductTableField";
export { ProductUpcAllocationModel } from "./ProductUpcAllocationModel";
export type { IProductUpcAllocationModel } from "./IProductUpcAllocationModel";
export { ProductUploadModel } from "./ProductUploadModel";
export type { IProductUploadModel } from "./IProductUploadModel";
export { SelectPrdFileupload } from "./SelectPrdFileupload";
export type { ISelectPrdFileupload } from "./ISelectPrdFileupload";
export { SelectProductSaveCheckListRequestModel } from "./SelectProductSaveCheckListRequestModel";
export type { ISelectProductSaveCheckListRequestModel } from "./ISelectProductSaveCheckListRequestModel";
export { ProductActivityReportFilter } from "./ProductActivityReportFilter";
export type { IProductActivityReportFilter } from "./IProductActivityReportFilter";
export { ApproveSuggestProductRequestModel } from "./ApproveSuggestProductRequestModel";
export type { IApproveSuggestProductRequestModel } from "./IApproveSuggestProductRequestModel";
export { SuggestedProductRequestModel } from "./SuggestedProductRequestModel";
export type { ISuggestedProductRequestModel } from "./ISuggestedProductRequestModel";
export { NewUserEmailModel } from "./NewUserEmailModel";
export type { INewUserEmailModel } from "./INewUserEmailModel";
export { BaseResponseModel } from "./BaseResponseModel";
export type { IBaseResponseModel } from "./IBaseResponseModel";
export { DashBoardResponseModel } from "./DashBoardResponseModel";
export type { IDashBoardResponseModel } from "./IDashBoardResponseModel";
export { DataMigrationThroughApiResponseModel } from "./DataMigrationThroughApiResponseModel";
export type { IDataMigrationThroughApiResponseModel } from "./IDataMigrationThroughApiResponseModel";
export { FileUploadResponse } from "./FileUploadResponse";
export type { IFileUploadResponse } from "./IFileUploadResponse";
export { ProductResponse } from "./ProductResponse";
export type { IProductResponse } from "./IProductResponse";
export { SuggestedProductResponseModel } from "./SuggestedProductResponseModel";
export type { ISuggestedProductResponseModel } from "./ISuggestedProductResponseModel";
export { UserResponseModel } from "./UserResponseModel";
export type { IUserResponseModel } from "./IUserResponseModel";
export { NutritionalInformationModel } from "./NutritionalInformationModel";
export type { INutritionalInformationModel } from "./INutritionalInformationModel";
export { QueryAllergenModel } from "./QueryAllergenModel";
export type { IQueryAllergenModel } from "./IQueryAllergenModel";
export { QueryAllergenModelFilter } from "./QueryAllergenModelFilter";
export type { IQueryAllergenModelFilter } from "./IQueryAllergenModelFilter";
export { QueryAllergenModelOrderBy } from "./QueryAllergenModelOrderBy";
export type { IQueryAllergenModelOrderBy } from "./IQueryAllergenModelOrderBy";
export { QueryAllergenModelPagedQueryResult } from "./QueryAllergenModelPagedQueryResult";
export type { IQueryAllergenModelPagedQueryResult } from "./IQueryAllergenModelPagedQueryResult";
export { QueryAllergenModelSearchQuery } from "./QueryAllergenModelSearchQuery";
export type { IQueryAllergenModelSearchQuery } from "./IQueryAllergenModelSearchQuery";
export { QueryCategoryModel } from "./QueryCategoryModel";
export type { IQueryCategoryModel } from "./IQueryCategoryModel";
export { QueryCategoryModelFilter } from "./QueryCategoryModelFilter";
export type { IQueryCategoryModelFilter } from "./IQueryCategoryModelFilter";
export { QueryCategoryModelOrderBy } from "./QueryCategoryModelOrderBy";
export type { IQueryCategoryModelOrderBy } from "./IQueryCategoryModelOrderBy";
export { QueryCategoryModelPagedQueryResult } from "./QueryCategoryModelPagedQueryResult";
export type { IQueryCategoryModelPagedQueryResult } from "./IQueryCategoryModelPagedQueryResult";
export { QueryCategoryModelSearchQuery } from "./QueryCategoryModelSearchQuery";
export type { IQueryCategoryModelSearchQuery } from "./IQueryCategoryModelSearchQuery";
export { QueryDefinedFilterModel } from "./QueryDefinedFilterModel";
export type { IQueryDefinedFilterModel } from "./IQueryDefinedFilterModel";
export { QueryDefinedFilterModelFilter } from "./QueryDefinedFilterModelFilter";
export type { IQueryDefinedFilterModelFilter } from "./IQueryDefinedFilterModelFilter";
export { QueryDefinedFilterModelOrderBy } from "./QueryDefinedFilterModelOrderBy";
export type { IQueryDefinedFilterModelOrderBy } from "./IQueryDefinedFilterModelOrderBy";
export { QueryDefinedFilterModelPagedQueryResult } from "./QueryDefinedFilterModelPagedQueryResult";
export type { IQueryDefinedFilterModelPagedQueryResult } from "./IQueryDefinedFilterModelPagedQueryResult";
export { QueryDefinedFilterModelSearchQuery } from "./QueryDefinedFilterModelSearchQuery";
export type { IQueryDefinedFilterModelSearchQuery } from "./IQueryDefinedFilterModelSearchQuery";
export { QueryDistributorModel } from "./QueryDistributorModel";
export type { IQueryDistributorModel } from "./IQueryDistributorModel";
export { QueryDistributorModelFilter } from "./QueryDistributorModelFilter";
export type { IQueryDistributorModelFilter } from "./IQueryDistributorModelFilter";
export { QueryDistributorModelOrderBy } from "./QueryDistributorModelOrderBy";
export type { IQueryDistributorModelOrderBy } from "./IQueryDistributorModelOrderBy";
export { QueryDistributorModelPagedQueryResult } from "./QueryDistributorModelPagedQueryResult";
export type { IQueryDistributorModelPagedQueryResult } from "./IQueryDistributorModelPagedQueryResult";
export { QueryDistributorModelSearchQuery } from "./QueryDistributorModelSearchQuery";
export type { IQueryDistributorModelSearchQuery } from "./IQueryDistributorModelSearchQuery";
export { QueryErrorLogModel } from "./QueryErrorLogModel";
export type { IQueryErrorLogModel } from "./IQueryErrorLogModel";
export { QueryErrorLogModelFilter } from "./QueryErrorLogModelFilter";
export type { IQueryErrorLogModelFilter } from "./IQueryErrorLogModelFilter";
export { QueryErrorLogModelOrderBy } from "./QueryErrorLogModelOrderBy";
export type { IQueryErrorLogModelOrderBy } from "./IQueryErrorLogModelOrderBy";
export { QueryErrorLogModelPagedQueryResult } from "./QueryErrorLogModelPagedQueryResult";
export type { IQueryErrorLogModelPagedQueryResult } from "./IQueryErrorLogModelPagedQueryResult";
export { QueryErrorLogModelSearchQuery } from "./QueryErrorLogModelSearchQuery";
export type { IQueryErrorLogModelSearchQuery } from "./IQueryErrorLogModelSearchQuery";
export { QueryIngredientModel } from "./QueryIngredientModel";
export type { IQueryIngredientModel } from "./IQueryIngredientModel";
export { QueryIngredientModelFilter } from "./QueryIngredientModelFilter";
export type { IQueryIngredientModelFilter } from "./IQueryIngredientModelFilter";
export { QueryIngredientModelOrderBy } from "./QueryIngredientModelOrderBy";
export type { IQueryIngredientModelOrderBy } from "./IQueryIngredientModelOrderBy";
export { QueryIngredientModelPagedQueryResult } from "./QueryIngredientModelPagedQueryResult";
export type { IQueryIngredientModelPagedQueryResult } from "./IQueryIngredientModelPagedQueryResult";
export { QueryIngredientModelSearchQuery } from "./QueryIngredientModelSearchQuery";
export type { IQueryIngredientModelSearchQuery } from "./IQueryIngredientModelSearchQuery";
export { QueryIocCategoryModel } from "./QueryIocCategoryModel";
export type { IQueryIocCategoryModel } from "./IQueryIocCategoryModel";
export { QueryIocCategoryModelFilter } from "./QueryIocCategoryModelFilter";
export type { IQueryIocCategoryModelFilter } from "./IQueryIocCategoryModelFilter";
export { QueryIocCategoryModelOrderBy } from "./QueryIocCategoryModelOrderBy";
export type { IQueryIocCategoryModelOrderBy } from "./IQueryIocCategoryModelOrderBy";
export { QueryIocCategoryModelPagedQueryResult } from "./QueryIocCategoryModelPagedQueryResult";
export type { IQueryIocCategoryModelPagedQueryResult } from "./IQueryIocCategoryModelPagedQueryResult";
export { QueryIocCategoryModelSearchQuery } from "./QueryIocCategoryModelSearchQuery";
export type { IQueryIocCategoryModelSearchQuery } from "./IQueryIocCategoryModelSearchQuery";
export { QueryManufacturerModel } from "./QueryManufacturerModel";
export type { IQueryManufacturerModel } from "./IQueryManufacturerModel";
export { QueryManufacturerModelFilter } from "./QueryManufacturerModelFilter";
export type { IQueryManufacturerModelFilter } from "./IQueryManufacturerModelFilter";
export { QueryManufacturerModelOrderBy } from "./QueryManufacturerModelOrderBy";
export type { IQueryManufacturerModelOrderBy } from "./IQueryManufacturerModelOrderBy";
export { QueryManufacturerModelPagedQueryResult } from "./QueryManufacturerModelPagedQueryResult";
export type { IQueryManufacturerModelPagedQueryResult } from "./IQueryManufacturerModelPagedQueryResult";
export { QueryManufacturerModelSearchQuery } from "./QueryManufacturerModelSearchQuery";
export type { IQueryManufacturerModelSearchQuery } from "./IQueryManufacturerModelSearchQuery";
export { QueryMonthlyNumberModel } from "./QueryMonthlyNumberModel";
export type { IQueryMonthlyNumberModel } from "./IQueryMonthlyNumberModel";
export { QueryMonthlyNumberModelFilter } from "./QueryMonthlyNumberModelFilter";
export type { IQueryMonthlyNumberModelFilter } from "./IQueryMonthlyNumberModelFilter";
export { QueryMonthlyNumberModelOrderBy } from "./QueryMonthlyNumberModelOrderBy";
export type { IQueryMonthlyNumberModelOrderBy } from "./IQueryMonthlyNumberModelOrderBy";
export { QueryMonthlyNumberModelPagedQueryResult } from "./QueryMonthlyNumberModelPagedQueryResult";
export type { IQueryMonthlyNumberModelPagedQueryResult } from "./IQueryMonthlyNumberModelPagedQueryResult";
export { QueryMonthlyNumberModelSearchQuery } from "./QueryMonthlyNumberModelSearchQuery";
export type { IQueryMonthlyNumberModelSearchQuery } from "./IQueryMonthlyNumberModelSearchQuery";
export { QueryOneWorldSyncProductModel } from "./QueryOneWorldSyncProductModel";
export type { IQueryOneWorldSyncProductModel } from "./IQueryOneWorldSyncProductModel";
export { QueryOneWorldSyncProductModelFilter } from "./QueryOneWorldSyncProductModelFilter";
export type { IQueryOneWorldSyncProductModelFilter } from "./IQueryOneWorldSyncProductModelFilter";
export { QueryOneWorldSyncProductModelOrderBy } from "./QueryOneWorldSyncProductModelOrderBy";
export type { IQueryOneWorldSyncProductModelOrderBy } from "./IQueryOneWorldSyncProductModelOrderBy";
export { QueryOneWorldSyncProductModelPagedQueryResult } from "./QueryOneWorldSyncProductModelPagedQueryResult";
export type { IQueryOneWorldSyncProductModelPagedQueryResult } from "./IQueryOneWorldSyncProductModelPagedQueryResult";
export { QueryOneWorldSyncProductModelSearchQuery } from "./QueryOneWorldSyncProductModelSearchQuery";
export type { IQueryOneWorldSyncProductModelSearchQuery } from "./IQueryOneWorldSyncProductModelSearchQuery";
export { QueryProductModel } from "./QueryProductModel";
export type { IQueryProductModel } from "./IQueryProductModel";
export { QueryProductModelFilter } from "./QueryProductModelFilter";
export type { IQueryProductModelFilter } from "./IQueryProductModelFilter";
export { QueryProductModelOrderBy } from "./QueryProductModelOrderBy";
export type { IQueryProductModelOrderBy } from "./IQueryProductModelOrderBy";
export { QueryProductModelPagedQueryResult } from "./QueryProductModelPagedQueryResult";
export type { IQueryProductModelPagedQueryResult } from "./IQueryProductModelPagedQueryResult";
export { QueryProductModelSearchQuery } from "./QueryProductModelSearchQuery";
export type { IQueryProductModelSearchQuery } from "./IQueryProductModelSearchQuery";
export { QueryRoleModel } from "./QueryRoleModel";
export type { IQueryRoleModel } from "./IQueryRoleModel";
export { QueryRoleModelFilter } from "./QueryRoleModelFilter";
export type { IQueryRoleModelFilter } from "./IQueryRoleModelFilter";
export { QueryRoleModelOrderBy } from "./QueryRoleModelOrderBy";
export type { IQueryRoleModelOrderBy } from "./IQueryRoleModelOrderBy";
export { QueryRoleModelPagedQueryResult } from "./QueryRoleModelPagedQueryResult";
export type { IQueryRoleModelPagedQueryResult } from "./IQueryRoleModelPagedQueryResult";
export { QueryRoleModelSearchQuery } from "./QueryRoleModelSearchQuery";
export type { IQueryRoleModelSearchQuery } from "./IQueryRoleModelSearchQuery";
export { QuerySchoolDistrictModel } from "./QuerySchoolDistrictModel";
export type { IQuerySchoolDistrictModel } from "./IQuerySchoolDistrictModel";
export { QuerySchoolDistrictModelFilter } from "./QuerySchoolDistrictModelFilter";
export type { IQuerySchoolDistrictModelFilter } from "./IQuerySchoolDistrictModelFilter";
export { QuerySchoolDistrictModelOrderBy } from "./QuerySchoolDistrictModelOrderBy";
export type { IQuerySchoolDistrictModelOrderBy } from "./IQuerySchoolDistrictModelOrderBy";
export { QuerySchoolDistrictModelPagedQueryResult } from "./QuerySchoolDistrictModelPagedQueryResult";
export type { IQuerySchoolDistrictModelPagedQueryResult } from "./IQuerySchoolDistrictModelPagedQueryResult";
export { QuerySchoolDistrictModelSearchQuery } from "./QuerySchoolDistrictModelSearchQuery";
export type { IQuerySchoolDistrictModelSearchQuery } from "./IQuerySchoolDistrictModelSearchQuery";
export { QueryStateModel } from "./QueryStateModel";
export type { IQueryStateModel } from "./IQueryStateModel";
export { QueryStateModelFilter } from "./QueryStateModelFilter";
export type { IQueryStateModelFilter } from "./IQueryStateModelFilter";
export { QueryStateModelOrderBy } from "./QueryStateModelOrderBy";
export type { IQueryStateModelOrderBy } from "./IQueryStateModelOrderBy";
export { QueryStateModelPagedQueryResult } from "./QueryStateModelPagedQueryResult";
export type { IQueryStateModelPagedQueryResult } from "./IQueryStateModelPagedQueryResult";
export { QueryStateModelSearchQuery } from "./QueryStateModelSearchQuery";
export type { IQueryStateModelSearchQuery } from "./IQueryStateModelSearchQuery";
export { QueryStorageTypeModel } from "./QueryStorageTypeModel";
export type { IQueryStorageTypeModel } from "./IQueryStorageTypeModel";
export { QueryStorageTypeModelFilter } from "./QueryStorageTypeModelFilter";
export type { IQueryStorageTypeModelFilter } from "./IQueryStorageTypeModelFilter";
export { QueryStorageTypeModelOrderBy } from "./QueryStorageTypeModelOrderBy";
export type { IQueryStorageTypeModelOrderBy } from "./IQueryStorageTypeModelOrderBy";
export { QueryStorageTypeModelPagedQueryResult } from "./QueryStorageTypeModelPagedQueryResult";
export type { IQueryStorageTypeModelPagedQueryResult } from "./IQueryStorageTypeModelPagedQueryResult";
export { QueryStorageTypeModelSearchQuery } from "./QueryStorageTypeModelSearchQuery";
export type { IQueryStorageTypeModelSearchQuery } from "./IQueryStorageTypeModelSearchQuery";
export { QuerySubCategoryModel } from "./QuerySubCategoryModel";
export type { IQuerySubCategoryModel } from "./IQuerySubCategoryModel";
export { QuerySubCategoryModelFilter } from "./QuerySubCategoryModelFilter";
export type { IQuerySubCategoryModelFilter } from "./IQuerySubCategoryModelFilter";
export { QuerySubCategoryModelOrderBy } from "./QuerySubCategoryModelOrderBy";
export type { IQuerySubCategoryModelOrderBy } from "./IQuerySubCategoryModelOrderBy";
export { QuerySubCategoryModelPagedQueryResult } from "./QuerySubCategoryModelPagedQueryResult";
export type { IQuerySubCategoryModelPagedQueryResult } from "./IQuerySubCategoryModelPagedQueryResult";
export { QuerySubCategoryModelSearchQuery } from "./QuerySubCategoryModelSearchQuery";
export type { IQuerySubCategoryModelSearchQuery } from "./IQuerySubCategoryModelSearchQuery";
export { QueryUserActionLogModel } from "./QueryUserActionLogModel";
export type { IQueryUserActionLogModel } from "./IQueryUserActionLogModel";
export { QueryUserActionLogModelFilter } from "./QueryUserActionLogModelFilter";
export type { IQueryUserActionLogModelFilter } from "./IQueryUserActionLogModelFilter";
export { QueryUserActionLogModelOrderBy } from "./QueryUserActionLogModelOrderBy";
export type { IQueryUserActionLogModelOrderBy } from "./IQueryUserActionLogModelOrderBy";
export { QueryUserActionLogModelPagedQueryResult } from "./QueryUserActionLogModelPagedQueryResult";
export type { IQueryUserActionLogModelPagedQueryResult } from "./IQueryUserActionLogModelPagedQueryResult";
export { QueryUserActionLogModelSearchQuery } from "./QueryUserActionLogModelSearchQuery";
export type { IQueryUserActionLogModelSearchQuery } from "./IQueryUserActionLogModelSearchQuery";
export { QueryUserModel } from "./QueryUserModel";
export type { IQueryUserModel } from "./IQueryUserModel";
export { QueryUserModelFilter } from "./QueryUserModelFilter";
export type { IQueryUserModelFilter } from "./IQueryUserModelFilter";
export { QueryUserModelOrderBy } from "./QueryUserModelOrderBy";
export type { IQueryUserModelOrderBy } from "./IQueryUserModelOrderBy";
export { QueryUserModelPagedQueryResult } from "./QueryUserModelPagedQueryResult";
export type { IQueryUserModelPagedQueryResult } from "./IQueryUserModelPagedQueryResult";
export { QueryUserModelSearchQuery } from "./QueryUserModelSearchQuery";
export type { IQueryUserModelSearchQuery } from "./IQueryUserModelSearchQuery";
export { SaveAllergenModel } from "./SaveAllergenModel";
export type { ISaveAllergenModel } from "./ISaveAllergenModel";
export { SaveCategoryModel } from "./SaveCategoryModel";
export type { ISaveCategoryModel } from "./ISaveCategoryModel";
export { SaveDefinedFilterModel } from "./SaveDefinedFilterModel";
export type { ISaveDefinedFilterModel } from "./ISaveDefinedFilterModel";
export { SaveDistributorModel } from "./SaveDistributorModel";
export type { ISaveDistributorModel } from "./ISaveDistributorModel";
export { SaveIngredientModel } from "./SaveIngredientModel";
export type { ISaveIngredientModel } from "./ISaveIngredientModel";
export { SaveManufacturerModel } from "./SaveManufacturerModel";
export type { ISaveManufacturerModel } from "./ISaveManufacturerModel";
export { SaveMonthlyNumberModel } from "./SaveMonthlyNumberModel";
export type { ISaveMonthlyNumberModel } from "./ISaveMonthlyNumberModel";
export { SaveOneWorldSyncProductModel } from "./SaveOneWorldSyncProductModel";
export type { ISaveOneWorldSyncProductModel } from "./ISaveOneWorldSyncProductModel";
export { SaveProductModel } from "./SaveProductModel";
export type { ISaveProductModel } from "./ISaveProductModel";
export { SaveSchoolDistrictModel } from "./SaveSchoolDistrictModel";
export type { ISaveSchoolDistrictModel } from "./ISaveSchoolDistrictModel";
export { SaveStorageTypeModel } from "./SaveStorageTypeModel";
export type { ISaveStorageTypeModel } from "./ISaveStorageTypeModel";
export { SaveSubCategoryModel } from "./SaveSubCategoryModel";
export type { ISaveSubCategoryModel } from "./ISaveSubCategoryModel";
export { SaveUserModel } from "./SaveUserModel";
export type { ISaveUserModel } from "./ISaveUserModel";
export { RoleMst } from "./RoleMst";
export type { IRoleMst } from "./IRoleMst";
export { ProblemDetails } from "./ProblemDetails";
export type { IProblemDetails } from "./IProblemDetails";
