//
// This file is generated. Do not edit manually.
//
// @applicationName: GreenOnion.API
// @applicationDescription: GreenOnion.API - 1.0.0.0
// @applicationVersion: 1.0.0.0
//
// @ts-nocheck
// eslint-disable @typescript-eslint/no-unused-vars
// Clients
export type { default as IAllergenClient } from "./IAllergenClient";  
export type { default as ICategoryClient } from "./ICategoryClient";  
export type { default as IDashBoardClient } from "./IDashBoardClient";  
export type { default as IDataMigrationThroughApiClient } from "./IDataMigrationThroughApiClient";  
export type { default as IDefinedFilterClient } from "./IDefinedFilterClient";  
export type { default as IDistributorClient } from "./IDistributorClient";  
export type { default as IErrorLogClient } from "./IErrorLogClient";  
export type { default as IIIocCategoryClient } from "./IIIocCategoryClient";  
export type { default as IIngredientClient } from "./IIngredientClient";  
export type { default as IManufacturerClient } from "./IManufacturerClient";  
export type { default as IMonthlyNumberClient } from "./IMonthlyNumberClient";  
export type { default as IOneWorldSyncProductClient } from "./IOneWorldSyncProductClient";  
export type { default as IProductClient } from "./IProductClient";  
export type { default as IReportClient } from "./IReportClient";  
export type { default as IRoleClient } from "./IRoleClient";  
export type { default as ISchoolDistrictClient } from "./ISchoolDistrictClient";  
export type { default as IStateClient } from "./IStateClient";  
export type { default as IStorageTypeClient } from "./IStorageTypeClient";  
export type { default as ISubCategoryClient } from "./ISubCategoryClient";  
export type { default as ISuggestedProductClient } from "./ISuggestedProductClient";  
export type { default as IUserClient } from "./IUserClient";  
export type { default as IUserActionLogClient } from "./IUserActionLogClient";  
export type { default as IApiHealthClient } from "./IApiHealthClient";  


// Models
export type {
    IContentReference, 
    IFilterParameter, 
    IOrderDirections, 
    IMessageLevels, 
    IResultMessage, 
    IFileHeader, 
    IFileHeaderData, 
    IFileStatus, 
    IMappingFieldData, 
    IProductCheck, 
    IProductGtinAllocationModel, 
    IProductTableField, 
    IProductUpcAllocationModel, 
    IProductUploadModel, 
    ISelectPrdFileupload, 
    ISelectProductSaveCheckListRequestModel, 
    IProductActivityReportFilter, 
    IApproveSuggestProductRequestModel, 
    ISuggestedProductRequestModel, 
    INewUserEmailModel, 
    IBaseResponseModel, 
    IDashBoardResponseModel, 
    IDataMigrationThroughApiResponseModel, 
    IFileUploadResponse, 
    IProductResponse, 
    ISuggestedProductResponseModel, 
    IUserResponseModel, 
    INutritionalInformationModel, 
    IQueryAllergenModel, 
    IQueryAllergenModelFilter, 
    IQueryAllergenModelOrderBy, 
    IQueryAllergenModelPagedQueryResult, 
    IQueryAllergenModelSearchQuery, 
    IQueryCategoryModel, 
    IQueryCategoryModelFilter, 
    IQueryCategoryModelOrderBy, 
    IQueryCategoryModelPagedQueryResult, 
    IQueryCategoryModelSearchQuery, 
    IQueryDefinedFilterModel, 
    IQueryDefinedFilterModelFilter, 
    IQueryDefinedFilterModelOrderBy, 
    IQueryDefinedFilterModelPagedQueryResult, 
    IQueryDefinedFilterModelSearchQuery, 
    IQueryDistributorModel, 
    IQueryDistributorModelFilter, 
    IQueryDistributorModelOrderBy, 
    IQueryDistributorModelPagedQueryResult, 
    IQueryDistributorModelSearchQuery, 
    IQueryErrorLogModel, 
    IQueryErrorLogModelFilter, 
    IQueryErrorLogModelOrderBy, 
    IQueryErrorLogModelPagedQueryResult, 
    IQueryErrorLogModelSearchQuery, 
    IQueryIngredientModel, 
    IQueryIngredientModelFilter, 
    IQueryIngredientModelOrderBy, 
    IQueryIngredientModelPagedQueryResult, 
    IQueryIngredientModelSearchQuery, 
    IQueryIocCategoryModel, 
    IQueryIocCategoryModelFilter, 
    IQueryIocCategoryModelOrderBy, 
    IQueryIocCategoryModelPagedQueryResult, 
    IQueryIocCategoryModelSearchQuery, 
    IQueryManufacturerModel, 
    IQueryManufacturerModelFilter, 
    IQueryManufacturerModelOrderBy, 
    IQueryManufacturerModelPagedQueryResult, 
    IQueryManufacturerModelSearchQuery, 
    IQueryMonthlyNumberModel, 
    IQueryMonthlyNumberModelFilter, 
    IQueryMonthlyNumberModelOrderBy, 
    IQueryMonthlyNumberModelPagedQueryResult, 
    IQueryMonthlyNumberModelSearchQuery, 
    IQueryOneWorldSyncProductModel, 
    IQueryOneWorldSyncProductModelFilter, 
    IQueryOneWorldSyncProductModelOrderBy, 
    IQueryOneWorldSyncProductModelPagedQueryResult, 
    IQueryOneWorldSyncProductModelSearchQuery, 
    IQueryProductModel, 
    IQueryProductModelFilter, 
    IQueryProductModelOrderBy, 
    IQueryProductModelPagedQueryResult, 
    IQueryProductModelSearchQuery, 
    IQueryRoleModel, 
    IQueryRoleModelFilter, 
    IQueryRoleModelOrderBy, 
    IQueryRoleModelPagedQueryResult, 
    IQueryRoleModelSearchQuery, 
    IQuerySchoolDistrictModel, 
    IQuerySchoolDistrictModelFilter, 
    IQuerySchoolDistrictModelOrderBy, 
    IQuerySchoolDistrictModelPagedQueryResult, 
    IQuerySchoolDistrictModelSearchQuery, 
    IQueryStateModel, 
    IQueryStateModelFilter, 
    IQueryStateModelOrderBy, 
    IQueryStateModelPagedQueryResult, 
    IQueryStateModelSearchQuery, 
    IQueryStorageTypeModel, 
    IQueryStorageTypeModelFilter, 
    IQueryStorageTypeModelOrderBy, 
    IQueryStorageTypeModelPagedQueryResult, 
    IQueryStorageTypeModelSearchQuery, 
    IQuerySubCategoryModel, 
    IQuerySubCategoryModelFilter, 
    IQuerySubCategoryModelOrderBy, 
    IQuerySubCategoryModelPagedQueryResult, 
    IQuerySubCategoryModelSearchQuery, 
    IQueryUserActionLogModel, 
    IQueryUserActionLogModelFilter, 
    IQueryUserActionLogModelOrderBy, 
    IQueryUserActionLogModelPagedQueryResult, 
    IQueryUserActionLogModelSearchQuery, 
    IQueryUserModel, 
    IQueryUserModelFilter, 
    IQueryUserModelOrderBy, 
    IQueryUserModelPagedQueryResult, 
    IQueryUserModelSearchQuery, 
    ISaveAllergenModel, 
    ISaveCategoryModel, 
    ISaveDefinedFilterModel, 
    ISaveDistributorModel, 
    ISaveIngredientModel, 
    ISaveManufacturerModel, 
    ISaveMonthlyNumberModel, 
    ISaveOneWorldSyncProductModel, 
    ISaveProductModel, 
    ISaveSchoolDistrictModel, 
    ISaveStorageTypeModel, 
    ISaveSubCategoryModel, 
    ISaveUserModel, 
    IRoleMst, 
    IProblemDetails, 
} from "./Models";

export {
    ZContentReference,
    ZFilterParameter,
    ZOrderDirections,
    ZMessageLevels,
    ZResultMessage,
    ZFileHeader,
    ZFileHeaderData,
    ZFileStatus,
    ZMappingFieldData,
    ZProductCheck,
    ZProductGtinAllocationModel,
    ZProductTableField,
    ZProductUpcAllocationModel,
    ZProductUploadModel,
    ZSelectPrdFileupload,
    ZSelectProductSaveCheckListRequestModel,
    ZProductActivityReportFilter,
    ZApproveSuggestProductRequestModel,
    ZSuggestedProductRequestModel,
    ZNewUserEmailModel,
    ZBaseResponseModel,
    ZDashBoardResponseModel,
    ZDataMigrationThroughApiResponseModel,
    ZFileUploadResponse,
    ZProductResponse,
    ZSuggestedProductResponseModel,
    ZUserResponseModel,
    ZNutritionalInformationModel,
    ZQueryAllergenModel,
    ZQueryAllergenModelFilter,
    ZQueryAllergenModelOrderBy,
    ZQueryAllergenModelPagedQueryResult,
    ZQueryAllergenModelSearchQuery,
    ZQueryCategoryModel,
    ZQueryCategoryModelFilter,
    ZQueryCategoryModelOrderBy,
    ZQueryCategoryModelPagedQueryResult,
    ZQueryCategoryModelSearchQuery,
    ZQueryDefinedFilterModel,
    ZQueryDefinedFilterModelFilter,
    ZQueryDefinedFilterModelOrderBy,
    ZQueryDefinedFilterModelPagedQueryResult,
    ZQueryDefinedFilterModelSearchQuery,
    ZQueryDistributorModel,
    ZQueryDistributorModelFilter,
    ZQueryDistributorModelOrderBy,
    ZQueryDistributorModelPagedQueryResult,
    ZQueryDistributorModelSearchQuery,
    ZQueryErrorLogModel,
    ZQueryErrorLogModelFilter,
    ZQueryErrorLogModelOrderBy,
    ZQueryErrorLogModelPagedQueryResult,
    ZQueryErrorLogModelSearchQuery,
    ZQueryIngredientModel,
    ZQueryIngredientModelFilter,
    ZQueryIngredientModelOrderBy,
    ZQueryIngredientModelPagedQueryResult,
    ZQueryIngredientModelSearchQuery,
    ZQueryIocCategoryModel,
    ZQueryIocCategoryModelFilter,
    ZQueryIocCategoryModelOrderBy,
    ZQueryIocCategoryModelPagedQueryResult,
    ZQueryIocCategoryModelSearchQuery,
    ZQueryManufacturerModel,
    ZQueryManufacturerModelFilter,
    ZQueryManufacturerModelOrderBy,
    ZQueryManufacturerModelPagedQueryResult,
    ZQueryManufacturerModelSearchQuery,
    ZQueryMonthlyNumberModel,
    ZQueryMonthlyNumberModelFilter,
    ZQueryMonthlyNumberModelOrderBy,
    ZQueryMonthlyNumberModelPagedQueryResult,
    ZQueryMonthlyNumberModelSearchQuery,
    ZQueryOneWorldSyncProductModel,
    ZQueryOneWorldSyncProductModelFilter,
    ZQueryOneWorldSyncProductModelOrderBy,
    ZQueryOneWorldSyncProductModelPagedQueryResult,
    ZQueryOneWorldSyncProductModelSearchQuery,
    ZQueryProductModel,
    ZQueryProductModelFilter,
    ZQueryProductModelOrderBy,
    ZQueryProductModelPagedQueryResult,
    ZQueryProductModelSearchQuery,
    ZQueryRoleModel,
    ZQueryRoleModelFilter,
    ZQueryRoleModelOrderBy,
    ZQueryRoleModelPagedQueryResult,
    ZQueryRoleModelSearchQuery,
    ZQuerySchoolDistrictModel,
    ZQuerySchoolDistrictModelFilter,
    ZQuerySchoolDistrictModelOrderBy,
    ZQuerySchoolDistrictModelPagedQueryResult,
    ZQuerySchoolDistrictModelSearchQuery,
    ZQueryStateModel,
    ZQueryStateModelFilter,
    ZQueryStateModelOrderBy,
    ZQueryStateModelPagedQueryResult,
    ZQueryStateModelSearchQuery,
    ZQueryStorageTypeModel,
    ZQueryStorageTypeModelFilter,
    ZQueryStorageTypeModelOrderBy,
    ZQueryStorageTypeModelPagedQueryResult,
    ZQueryStorageTypeModelSearchQuery,
    ZQuerySubCategoryModel,
    ZQuerySubCategoryModelFilter,
    ZQuerySubCategoryModelOrderBy,
    ZQuerySubCategoryModelPagedQueryResult,
    ZQuerySubCategoryModelSearchQuery,
    ZQueryUserActionLogModel,
    ZQueryUserActionLogModelFilter,
    ZQueryUserActionLogModelOrderBy,
    ZQueryUserActionLogModelPagedQueryResult,
    ZQueryUserActionLogModelSearchQuery,
    ZQueryUserModel,
    ZQueryUserModelFilter,
    ZQueryUserModelOrderBy,
    ZQueryUserModelPagedQueryResult,
    ZQueryUserModelSearchQuery,
    ZSaveAllergenModel,
    ZSaveCategoryModel,
    ZSaveDefinedFilterModel,
    ZSaveDistributorModel,
    ZSaveIngredientModel,
    ZSaveManufacturerModel,
    ZSaveMonthlyNumberModel,
    ZSaveOneWorldSyncProductModel,
    ZSaveProductModel,
    ZSaveSchoolDistrictModel,
    ZSaveStorageTypeModel,
    ZSaveSubCategoryModel,
    ZSaveUserModel,
    ZRoleMst,
    ZProblemDetails,
} from "./Schema";
